// This file is auto-generated by @hey-api/openapi-ts

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const NewsArticlePublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        source_name: {
            type: 'string',
            title: 'Source Name'
        },
        published_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published At'
        },
        ingested_at: {
            type: 'string',
            format: 'date-time',
            title: 'Ingested At'
        },
        content: {
            type: 'string',
            title: 'Content'
        }
    },
    type: 'object',
    required: ['id', 'title', 'url', 'source_name', 'published_at', 'ingested_at', 'content'],
    title: 'NewsArticlePublic',
    description: 'Public schema for news article API responses.'
} as const;

export const NewsListResponseSchema = {
    properties: {
        articles: {
            items: {
                '$ref': '#/components/schemas/NewsArticlePublic'
            },
            type: 'array',
            title: 'Articles'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['articles', 'count'],
    title: 'NewsListResponse',
    description: 'Response model for news article list endpoint.'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;