// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { HealthHealthCheckResponse, NewsGetNewsArticlesData, NewsGetNewsArticlesResponse, NewsTriggerManualIngestionData, NewsTriggerManualIngestionResponse, NewsGetNewsSourcesResponse } from './types.gen';

export class HealthService {
    /**
     * Health Check
     * Health check endpoint for Docker healthcheck.
     * @returns string Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<HealthHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/health-check/'
        });
    }
}

export class NewsService {
    /**
     * Get News Articles
     * Get recent news articles with optional source filtering.
     * @param data The data for the request.
     * @param data.limit
     * @param data.sourceName
     * @returns NewsListResponse Successful Response
     * @throws ApiError
     */
    public static getNewsArticles(data: NewsGetNewsArticlesData = {}): CancelablePromise<NewsGetNewsArticlesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/news/',
            query: {
                limit: data.limit,
                source_name: data.sourceName
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Trigger Manual Ingestion
     * Manually trigger news ingestion.
     *
     * Args:
     * source_name: Optional source name. If provided, ingests only that source.
     * If omitted, ingests all active sources.
     *
     * Returns:
     * Success response with ingestion statistics
     *
     * Raises:
     * HTTPException: 404 if source_name not found, 500 if ingestion fails
     * @param data The data for the request.
     * @param data.sourceName
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static triggerManualIngestion(data: NewsTriggerManualIngestionData = {}): CancelablePromise<NewsTriggerManualIngestionResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/news/ingest/',
            query: {
                source_name: data.sourceName
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get News Sources
     * Get all active news sources.
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static getNewsSources(): CancelablePromise<NewsGetNewsSourcesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/news/sources'
        });
    }
}