// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Public schema for news article API responses.
 */
export type NewsArticlePublic = {
    id: number;
    title: string;
    url: string;
    source_name: string;
    published_at: (string | null);
    ingested_at: string;
    content: string;
};

/**
 * Response model for news article list endpoint.
 */
export type NewsListResponse = {
    articles: Array<NewsArticlePublic>;
    count: number;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type HealthHealthCheckResponse = ({
    [key: string]: (string);
});

export type NewsGetNewsArticlesData = {
    limit?: number;
    sourceName?: (string | null);
};

export type NewsGetNewsArticlesResponse = (NewsListResponse);

export type NewsTriggerManualIngestionData = {
    sourceName?: (string | null);
};

export type NewsTriggerManualIngestionResponse = (unknown);

export type NewsGetNewsSourcesResponse = (unknown);